### ISSUE TITLE
Ajout compteur de production

### ISSUE THREAD

**Issue by ticed35** [Jeedom-Plugins-Extra/plugin-teleinfo#7]
Ajouter la gestion d'un second modem pour la production d'électricité.

**Comment by jmgfr** [comment]
Fermée sans commentaire.
Pour ma part j'utilise ce module pour la téléinfo.  En effet comme son l'indique je pense que ce module est fait pour cela.
Or j'ai du désactiver l'historique du compteur de production sinon la production est considérée comme consommation dans les statistiques.
De plus, s'il existe un mode multi-compteur compatible avec les appareils du commerce, il n'existe pas de moyen d'ajouter deux ports com différents, l'un pour la consommation, l'autre pour la production.
Au minimum, il faudrait pouvoir ajouter plusieurs ports com et définir, en fonction de l'ADCO, s'il s'agit de consommation ou de production, puisque les deux font de la téléinfo  (nom du plugin !) mais ne se gèrent pas de la même façon.

**Comment by ticed35** [comment]
La fonction vient tout juste d'être implémenté refait une recherche des mises à jours sur jeedom.
